class_name ArchipelagoModBase
extends Node

# Brotato Archipelago Multiworld Randomizer Client

const MOD_NAME = "RampagingHippy-Archipelago"

func _init(_modLoader = ModLoader):
	ModLoaderLog.info("Init", MOD_NAME)

	# ! We can't use `ModLoader` because the ModLoader instance isn't available
	# ! at this point in the mod's loading process. Instead, the class instance
	# ! is passed to a mod's `_init` func via the variable `modLoader`.
	# ! It will be available in any other places in your mod though, such as in
	# ! your _ready func.
	var dir = ModLoaderMod.get_unpacked_dir() + MOD_NAME + "/"
	var ext_dir = dir + "extensions/" # ! any script extensions should go in this folder, and should follow the same folder structure as vanilla

	# Add extensions
	var extension_files = [
		"main.gd", # Update consumable drop logic to spawn AP items
		"singletons/item_service.gd", # Drop AP consumables
		"ui/menus/pages/main_menu.gd", # Add AP connect button to main menu
		"ui/menus/title_screen/title_screen_menus.gd", # Swtich to connect menu when connect button is pressed
	]
	
	for ef in extension_files:
		ModLoaderMod.install_script_extension(ext_dir + ef)

	# Add translations
	# ! Load translations for your mod, if you need them.
	# ! Add translations by adding a CSV called "modname.csv" into the "translations" folder.
	# ! Godot will automatically generate a ".translation" file, eg "modname.en.translation".
	# ! Note that in this example, only the file called "modname.csv" is custom;
	# ! any other files in the "translations" folder were automatically generated by Godot
	ModLoaderMod.add_translation(dir + "translations/modname.en.translation")
	

func _ready()->void:
	ModLoaderLog.info("Ready", MOD_NAME)

	# ! This uses Godot's native `tr` func, which translates a string. You'll
	# ! find this particular string in the example CSV here: translations/modname.csv
	ModLoaderLog.info(str("Translation Demo: ", tr("MODNAME_READY_TEXT")), MOD_NAME)
	ModLoaderLog.success("Loaded", MOD_NAME)

	# var ContentLoader = get_node("/root/ModLoader/Darkly77-ContentLoader/ContentLoader")
	# var content_dir = "res://mods-unpacked/RampagingHippy-Archipelago/content_data/"
	# ContentLoader.load_data(content_dir + "ap_consumables.tres", MOD_NAME)
