class_name BrotatoApConstants

const CHARACTERS = [
	"Well Rounded",
    "Brawler",
    "Crazy",
    "Ranger",
    "Mage",
    "Chunky",
    "Old",
    "Lucky",
    "Mutant",
    "Generalist",
    "Loud",
    "Multitasker",
    "Wildling",
    "Pacifist",
    "Gladiator",
    "Saver",
    "Sick",
    "Farmer",
    "Ghost",
    "Speedy",
    "Entrepeneur",
    "Engineer",
    "Explorer",
    "Doctor",
    "Hunter",
    "Artificer",
    "Arms Dealer",
    "Streamer",
    "Cyborg",
    "Glutton",
    "Jack",
    "Lich",
    "Appentice",
    "Cryptid",
    "Fisherman",
    "Golem",
    "King",
    "Renegade",
    "One Armed",
    "Bull",
    "Soldier",
    "Masochist",
    "Knight",
    "Demon",
]

const GOLD_DROP_NAME_TO_VALUE = {
	"Gold (10)": 10,
	"Gold (25)": 25,
	"Gold (50)": 50,
	"Gold (100)": 100,
	"Gold (200)": 200,
}

const XP_ITEM_NAME_TO_VALUE = {
	"XP (5)": 5,
	"XP (10)": 10,
	"XP (25)": 25,
	"XP (50)": 50,
	"XP (100)": 100,
	"XP (250)": 250,
}