"""Download the requsted version of the Godot project recovery tools, GDRETools.

This tool is necessary for converting the release version of Brotato (i.e. the one
installed by Steam/GoG/Epic) back into its project structure with decompiled files and
assets, so we can then develop mods for it.

The release is assumed to be a version from teh GDRETools GitHub:
https://github.com/GDRETools/gdsdecomp. Look at the releases page there for valid
versions.

This script first checks if the requested version is downloaded, and does nothing if so,
unless the "-f/--force" flag is set. We write a custom file, "gdre_version.json", to the
output directory with the version requested, which is queried to make this check.
"""

import argparse
import json
import os
import shutil
import stat
import sys
import tempfile
import urllib.request
import zipfile
from pathlib import Path

_GDRETOOLS_DOWNLOAD_URL = (
    "https://github.com/GDRETools/gdsdecomp/releases/download/{version}/GDRE_tools-{version}-{platform}.zip"
)

parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
parser.add_argument("gdre_version", default=None, help="The release version of GDRE to download.")
parser.add_argument(
    "-o",
    "--outdir",
    type=Path,
    default=Path.cwd(),
    help="The directory to save the release into. Defaults to the current directory.",
)
parser.add_argument(
    "-f", "--force", action="store_true", help="Download and save even if the requested version is already downloaded."
)


def main():
    args = parser.parse_args()
    gdre_version: str = args.gdre_version
    outdir: Path = args.outdir
    force: bool = args.force
    version_file = outdir / "gdre_version.json"

    if not force and version_file.read_text():
        # Check if the requested version is already downloaded
        version_info = json.loads(version_file.read_text())
        downloaded_version = version_info["version"]
        if downloaded_version == gdre_version:
            print(f"Requested version {gdre_version} is already downloaded to this location, doing nothing.")
            sys.exit(0)

    platform: str
    match sys.platform:
        case "linux":
            platform = "linux"
        case "win32":
            platform = "windows"
        case "darwin":
            platform = "macos"
        case _:
            raise RuntimeError(f"Unknown platform {sys.platform}")

    download_url = _GDRETOOLS_DOWNLOAD_URL.format(version=gdre_version, platform=platform)

    print(f"Downloading release zip from {download_url}.")
    with tempfile.TemporaryDirectory() as td:
        td_path = Path(td)
        download_zipfile = td_path / "gdre_download.zip"
        urllib.request.urlretrieve(download_url, download_zipfile)
        if outdir.is_dir():
            print(f"Found existing dir {outdir}, removing.")
            shutil.rmtree(outdir)
        print(f"Extracting release to {outdir}.")
        with zipfile.ZipFile(download_zipfile, "r") as zf:
            zf.extractall(outdir)

    print(f"Saved {gdre_version} to {outdir}.")

    # Make the exe actually executable
    if sys.platform == "linux":
        exe_file = outdir / "gdre_tools.x86_64"
        print(f"Setting executable file {exe_file} as executable.")
        st = os.stat(exe_file)
        os.chmod(exe_file, st.st_mode | stat.S_IEXEC)

    # The version returned by the gdre_tools program doesn't match the version we
    # download. Save the downloaded version to a text file for use later/in other tools.
    version_file = outdir / "gdre_version.json"
    version_info = {
        "_note": f"THIS WAS AUTOGENERATED BY {Path(__file__).name}, IT IS NOT PART OF THE GDRE_TOOLS RELEASE.",
        "version": gdre_version,
    }
    print(f"Saving version info to {version_file}.")
    version_file.write_text(json.dumps(version_info, indent=4))

    print("Done.")


if __name__ == "__main__":
    main()
